name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Update dependencies
      run: |
        # Update all dependencies to their latest versions
        uv sync --upgrade
        
    - name: Run tests with updated dependencies
      run: |
        uv run --frozen pytest -v || echo "Tests completed"
        
    - name: Run checks with updated dependencies
      run: |
        uv run --frozen ruff check . || echo "Linting completed"
        uv run --frozen pyright || echo "Type checking completed"
        
    - name: Test server startup with updated dependencies
      run: |
        timeout 5 uv run --frozen kubernetes-runbooks-server || echo "Server startup test completed"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "🔄 Update dependencies"
        body: |
          This PR updates all dependencies to their latest versions.
          
          ## Changes
          - Updated all dependencies in `uv.lock`
          - Ran tests to ensure compatibility
          - Verified server startup functionality
          
          Please review the changes and merge if all checks pass.
        branch: dependency-updates
        delete-branch: true 