name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

jobs:
  checks:
    name: Run all checks
    uses: ./.github/workflows/shared.yml

  release-build:
    name: Build distribution packages
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --frozen --all-extras --dev

    - name: Build distribution packages
      run: uv build

    - name: Verify packages
      run: uv run --frozen twine check dist/*

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-dists
        path: dist/
        retention-days: 30

  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: 
      name: release
      url: https://pypi.org/project/kubernetes-runbooks-mcp-server/
    needs: [release-build]
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
      contents: read

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: release-dists
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true
        verbose: true
